version: "3"

services:
  golang:
    build:
      context: .
      dockerfile: ./build/package/golang/Dockerfile
    container_name: kakebo_echo_golang
    volumes:
      - ./:/go/src/kakebo-echo
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    platform: linux/amd64
    image: mysql:5.7.38
    container_name: echo_mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: local_password
      MYSQL_ROOT_PASSWORD: local_password
      TZ: "Asia/Tokyo"
    volumes:
      - echo-db-data:/var/lib/mysql
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

volumes:
  echo-db-data:
