version: '3'

services:
  golang:
    build:
      context: .
      dockerfile: ./build/package/golang/Dockerfile
    container_name: kakebo_echo_golang
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./:/go/src/kakebo-echo
    ports:
      - '8080:8080'
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=local_password
    tty: true
    restart: always
    user: root
    volumes:
      - postgresdb:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro

volumes:
  postgresdb:
    driver: local
